export const GAME_RESULT = {
  IN_PROGRESS: " ",
  LOST: "Lost",
  WON: "Won"
};
export const MAX_WRONG_GUESSES = 7;

export const PROGRAMING_LANGS = [
  "C",
  "CSharp",
  "CSS",
  "dart"
  // "delphi",
  // "elixir",
  // "erlang",
  // "fortran",
  // "golang",
  // "groovy",
  // "haskell",
  // "html",
  // "java",
  // "javascript",
  // "kotlin",
  // "matlab",
  // "objectivec",
  // "perl",
  // "php",
  // "python",
  // "r",
  // "ruby",
  // "rust",
  // "scala",
  // "sql",
  // "swift",
  // "typescript"
];

export const DATABASES = [
  "oracle",
  "mysql",
  "mssql",
  "postgresql",
  "mongodb",
  "ibmdb2",
  "redis",
  "elasticsearch",
  "sqlite",
  "msaccess",
  "cassandra",
  "mariadb",
  "splunk",
  "hive",
  "dynamodb",
  "teradata",
  "bigquery",
  "couchbase",
  "cosmosdb",
  "redshift",
  "prometheus",
  "ingres",
  "ignite",
  "pouchdb",
  "phoenix",
  "openbase"
];

export const MOVIES = [

 "fighter",
 "3 idiots",
 "shaitaan",
 "kalki",
 "rautu ka raaz",
 "sharmajee ki beti",
 "ishq vishk rebound",
 "maharaj",
 "auron mein kahan dum tha",
 "housefull 5",
 "sarfira",
 "hindustani 2",
 "bad newz",
 "vedaa",
 "dilwale dulhania le jayenge",
 "kabhi khushi kabhie gham",
 "lagaan",
 "zindagi na milegi dobara",
 "bajrangi bhaijaan",
 "pk",
 "dangal",
 "padmaavat",
 "bahubali",
 "bahubali 2 the conclusion",
 "chennai express",
 "my name is khan",
 "kuch kuch hota hai",
 "dil chahta hai",
 "kal ho naa ho",
 "kabir singh",
 "raazi",
 "uri the surgical strike",
 "andhadhun",
 "gully boy",
 "article 15",
 "super 30",
 "war",
 "chhichhore",
 "tanhaji: the unsung warrior",
 "shershaah",
 "radhe: your most wanted bhai",
 "bell bottom",
 "laal singh chaddha",
 "sooryavanshi",
 "bhool bhulaiya 2",
 "pathan",
 "rrr",
 "brahmastra",
 "rocky aur rani ki prem kahani",
 "jayeshbhai jordaar",
 "bhool bhulaiyaa 2",
 "shabaash mithu",

];


